#!/usr/bin/env python3
"""Check the docs, and write the page list the search index needs.

What it checks:
  1. every sidebar link opens a file, and every page is in a sidebar;
  2. every internal link is written from the site root ("/guide/install.md") and resolves, anchors too;
  3. every IDA address in a page is in the index (tools/data/addresses.json), a name next to an address
     is the index's name for it, and an RVA in a function table is the address minus the image base;
  4. with --cw-mod: every cw-mod.json key and every cwlink and ffinfo flag in the source is documented;
  5. nothing that must stay out of the docs is in them (local paths, keys, personal data);
  6. page shape: a title, a sources comment, and the word budget (a warning, not an error).

Usage:
  python tools/check_docs.py [--cw-mod <path to cw-mod>] [--write-index] [--words]

--write-index rewrites assets/pages.js from the sidebars.
--words prints the prose word count of every page.
Exit code 1 when an error was found.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = 0x7FF71CBC0000
SKIP_TOP = {"tools", "assets"}
SKIP_ANYWHERE = {".git", "node_modules", "__pycache__"}
INLINE_CODE_RE = re.compile(r"`[^`]*`")

LINK_RE = re.compile(r"(?<!\!)\[(?P<text>[^\]]*)\]\((?P<target>[^)\s]+)(?:\s+['\"][^)]*['\"])?\)")
IMAGE_RE = re.compile(r"!\[[^\]]*\]\((?P<target>[^)\s]+)(?:\s+['\"][^)]*['\"])?\)")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
VA_RE = re.compile(r"0x7FF7[0-9A-Fa-f]{8}\b")
HEX_RE = re.compile(r"0x[0-9A-Fa-f]+\b")
CODE_NAME_RE = re.compile(r"`([A-Za-z_~][A-Za-z0-9_:~]*)`")

SLUG_STRIP = re.compile(r"[ -⁯⸀-⹿\\'!\"#$%&()*+,./:;<=>?@\[\]^`{|}~]")
EMOJI = re.compile("[\U0001F000-\U0001FAFF☀-➿️]")

WORD_BUDGET = {"re": 600, "guide": 400}
BUDGET_SLACK = 1.15
# Pages that are tables or lists by nature.
BUDGET_EXEMPT = ("re/reference/", "guide/lists/", "glossary.md", "re/mapkit/crash-log.md")

FORBIDDEN = (
    (re.compile(r"[A-Za-z]:\\Users\\", re.I), "a Windows user path"),
    (re.compile(r"[A-Za-z]:\\Games\\", re.I), "a local game path"),
    (re.compile(r"\b[A-Za-z]:\\(?:tools|temp|Program Files)", re.I), "a local path"),
    (re.compile(r"/Users/[a-z0-9_.-]+/", re.I), "a user path"),
    (re.compile(r"[\w.+-]+@(?:gmail|outlook|hotmail|yahoo|proton)\.[a-z.]+", re.I), "an e-mail address"),
    (re.compile(r"BEGIN (?:RSA |EC )?PRIVATE KEY"), "a private key"),
    (re.compile(r"bb442e6d5002", re.I), "the MAC address from the captured login request"),
    (re.compile(r"\bBlob\(6\)\s+[0-9a-f]{12}\b", re.I), "a MAC address"),
    (re.compile(r"eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}"), "a token"),
)


def slugify(text: str, seen: dict[str, int]) -> str:
    """docsify 5's slugify (src/core/render/slugify.js), which runs on a heading's markdown text."""
    slug = text.strip()
    slug = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", slug)
    slug = EMOJI.sub("", slug)
    slug = re.sub(r"[A-Z]+", lambda m: m.group(0).lower(), slug)
    slug = re.sub(r"<[^>]+>", "", slug)
    slug = SLUG_STRIP.sub("", slug)
    slug = re.sub(r"\s", "-", slug)
    slug = re.sub(r"^(\d)", r"_\1", slug)
    count = seen.get(slug, -1) + 1
    seen[slug] = count
    return f"{slug}-{count}" if count else slug


class Page:
    def __init__(self, path: Path):
        self.path = path
        self.rel = path.relative_to(ROOT).as_posix()
        self.text = path.read_text(encoding="utf-8")
        self.lines = self.text.splitlines()
        self.generated = "<!-- generated by tools/" in self.text
        self.anchors: set[str] = set()
        self.title = ""
        self.prose_words = 0
        self._scan()

    def _scan(self) -> None:
        seen: dict[str, int] = {}
        in_code = False
        in_comment = False
        for line in self.lines:
            stripped = line.strip()
            if stripped.startswith("```"):
                in_code = not in_code
                continue
            if in_code:
                continue
            if "<!--" in stripped and "-->" not in stripped:
                in_comment = True
                continue
            if in_comment:
                if "-->" in stripped:
                    in_comment = False
                continue
            if stripped.startswith("<!--"):
                continue
            heading = HEADING_RE.match(line)
            if heading:
                text = re.sub(r"\s*:id=([\w-]+)\s*$", "", heading.group(2))
                custom = re.search(r":id=([\w-]+)\s*$", heading.group(2))
                slug = slugify(custom.group(1) if custom else text, seen)
                self.anchors.add(slug)
                if heading.group(1) == "#" and not self.title:
                    self.title = text
                continue
            if stripped.startswith("|") or not stripped:
                continue
            prose = re.sub(r"`[^`]*`", " x ", stripped)
            prose = LINK_RE.sub(lambda m: m.group("text"), prose)
            self.prose_words += len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'_-]*", prose))

    def body_lines(self):
        """(number, line) for every line outside fenced code and HTML comments."""
        in_code = False
        in_comment = False
        for number, line in enumerate(self.lines, 1):
            stripped = line.strip()
            if stripped.startswith("```"):
                in_code = not in_code
                continue
            if in_code:
                continue
            if in_comment:
                if "-->" in stripped:
                    in_comment = False
                continue
            if stripped.startswith("<!--"):
                if "-->" not in stripped:
                    in_comment = True
                continue
            yield number, line


def find_pages() -> list[Path]:
    pages = []
    for path in sorted(ROOT.rglob("*.md")):
        rel = path.relative_to(ROOT)
        # The repository's own tools/ and assets/ folders hold no pages; guide/tools/ does.
        if rel.parts[0] in SKIP_TOP or SKIP_ANYWHERE & set(rel.parts):
            continue
        pages.append(path)
    return pages


def resolve(target: str) -> tuple[Path | None, str]:
    """A root-absolute link target -> (file, anchor)."""
    path, _, anchor = target.partition("#")
    path = path.split("?", 1)[0]
    if not path.startswith("/"):
        return None, anchor
    rel = path.lstrip("/")
    if rel == "" or rel.endswith("/"):
        rel += "README.md"
    return ROOT / rel, anchor


def route_of(rel: str) -> str:
    if rel == "README.md":
        return "/"
    if rel.endswith("/README.md"):
        return "/" + rel[: -len("README.md")]
    return "/" + rel[: -len(".md")]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cw-mod", type=Path, help="path to a cw-mod checkout, for the coverage checks")
    parser.add_argument("--write-index", action="store_true", help="rewrite assets/pages.js")
    parser.add_argument("--words", action="store_true", help="print each page's prose word count")
    args = parser.parse_args()

    errors: list[str] = []
    warnings: list[str] = []
    paths = find_pages()
    pages = {p.relative_to(ROOT).as_posix(): Page(p) for p in paths}
    content = {rel: page for rel, page in pages.items() if not Path(rel).name.startswith("_")}
    sidebars = {rel: page for rel, page in pages.items() if Path(rel).name == "_sidebar.md"}

    # --- 1. sidebars ------------------------------------------------------------------------------
    in_sidebar: set[str] = set()
    ordered_routes: list[str] = []
    for rel, sidebar in sidebars.items():
        for number, raw_line in sidebar.body_lines():
            line = INLINE_CODE_RE.sub("", raw_line)
            for match in LINK_RE.finditer(line):
                target = match.group("target")
                if re.match(r"[a-z]+:", target):
                    continue
                file, _ = resolve(target)
                if file is None:
                    errors.append(f"{rel}:{number}: sidebar link '{target}' must start with '/'")
                    continue
                if not file.is_file():
                    errors.append(f"{rel}:{number}: sidebar link '{target}' has no file")
                    continue
                target_rel = file.relative_to(ROOT).as_posix()
                in_sidebar.add(target_rel)
                route = route_of(target_rel)
                if route not in ordered_routes:
                    ordered_routes.append(route)
    for rel in content:
        if rel not in in_sidebar:
            errors.append(f"{rel}: not listed in any _sidebar.md")

    # --- 2. links ---------------------------------------------------------------------------------
    for rel, page in pages.items():
        for number, raw_line in page.body_lines():
            line = INLINE_CODE_RE.sub("", raw_line)   # text in backticks is code, not a link
            for regex in (LINK_RE, IMAGE_RE):
                for match in regex.finditer(line):
                    target = match.group("target")
                    if re.match(r"(?:[a-z][a-z0-9+.-]*:|//)", target, re.I):
                        continue
                    if target.startswith("#"):
                        if target[1:] not in page.anchors:
                            errors.append(f"{rel}:{number}: no heading '{target}' on this page")
                        continue
                    file, anchor = resolve(target)
                    if file is None:
                        errors.append(f"{rel}:{number}: link '{target}' must start with '/' (links are written from the site root)")
                        continue
                    if not file.is_file():
                        errors.append(f"{rel}:{number}: link '{target}' has no file")
                        continue
                    if anchor:
                        target_rel = file.relative_to(ROOT).as_posix()
                        target_page = pages.get(target_rel)
                        if target_page is None:
                            errors.append(f"{rel}:{number}: link '{target}' has an anchor into a file that is not a page")
                        elif anchor not in target_page.anchors:
                            errors.append(f"{rel}:{number}: no heading '#{anchor}' in {target_rel}")

    # --- 3. addresses -----------------------------------------------------------------------------
    index_path = ROOT / "tools" / "data" / "addresses.json"
    known_vas: dict[int, set[str]] = {BASE: {"the image base"}}
    name_to_va: dict[str, int] = {}
    if index_path.is_file():
        index = json.loads(index_path.read_text(encoding="utf-8"))
        for entry in index["entries"]:
            va = int(entry["va"], 16)
            names = {entry["name"], *entry.get("also", [])}
            known_vas.setdefault(va, set()).update(names)
            for name in names:
                name_to_va.setdefault(name, va)
    else:
        warnings.append("tools/data/addresses.json is missing: run tools/gen_functions.py (addresses not checked)")

    if known_vas:
        for rel, page in content.items():
            if page.generated:
                continue
            # Fenced code is left out: a worked byte-math example names instruction addresses that are not symbols.
            for number, line in page.body_lines():
                vas = [int(m.group(0), 16) for m in VA_RE.finditer(line)]
                if not vas:
                    continue
                for va in vas:
                    if va not in known_vas:
                        errors.append(f"{rel}:{number}: address 0x{va:X} is not in the index (a typo, or run gen_functions.py)")
                if not line.lstrip().startswith("|"):
                    continue
                cells = [c.strip() for c in line.strip().strip("|").split("|")]
                row_names = [n for n in CODE_NAME_RE.findall(cells[0]) if n in name_to_va] if cells else []
                if len(row_names) == 1 and len(vas) == 1:
                    name, va = row_names[0], vas[0]
                    if name_to_va[name] != va and name not in known_vas.get(va, set()):
                        errors.append(f"{rel}:{number}: `{name}` is 0x{name_to_va[name]:X} in the index, the row says 0x{va:X}")
                if len(vas) == 1:
                    rva = vas[0] - BASE
                    others = [int(h, 16) for h in HEX_RE.findall(line) if not VA_RE.fullmatch(h)]
                    # A row that gives both forms must agree with itself.
                    plausible = [o for o in others if 0x1000 <= o < 0x20000000 and abs(o - rva) < 0x1000000]
                    if plausible and rva not in plausible:
                        errors.append(f"{rel}:{number}: RVA {', '.join(hex(o) for o in plausible)} does not match 0x{vas[0]:X} (expected 0x{rva:X})")

    # --- 4. coverage against the source -----------------------------------------------------------
    if args.cw_mod:
        cw_mod = args.cw_mod.resolve()

        def documented(page_rel: str, items: list[str], what: str) -> None:
            page = pages.get(page_rel)
            if page is None:
                warnings.append(f"{page_rel} is not written yet: {len(items)} {what} not checked")
                return
            for item in items:
                if f"`{item}`" not in page.text and f"`{item} " not in page.text and f'"{item}"' not in page.text:
                    errors.append(f"{page_rel}: {what} `{item}` is in the source but not on the page")

        settings = cw_mod / "client/game/settings.cpp"
        if settings.is_file():
            text = settings.read_text(encoding="utf-8", errors="replace")
            keys = re.findall(r'\{\s*"([a-z_]+)",\s*&Values::', text)
            keys += [k for k in ("name", "xuid", "mode", "ui_text", "mapkit_trace") if f'has("{k}")' in text]
            documented("guide/settings.md", sorted(set(keys)), "cw-mod.json key")
        for tool in ("cwlink", "ffinfo"):
            source = cw_mod / "mapkit" / tool / "main.cpp"
            if source.is_file():
                flags = set(re.findall(r'"(--[a-z][a-z0-9-]+)"', source.read_text(encoding="utf-8", errors="replace")))
                flags -= {"--name", "--name-client"}   # arguments cwlink passes to ACTS, not its own
                documented(f"guide/tools/{tool}.md", sorted(flags), f"{tool} flag")

    # --- 5. what must stay out --------------------------------------------------------------------
    scanned: list[tuple[str, list[str]]] = [(rel, page.lines) for rel, page in pages.items()]
    others = list(ROOT.glob("*.html")) + list((ROOT / "assets").glob("*.*"))
    others += [p for top in ("guide", "re") for p in (ROOT / top).rglob("*.txt")]
    for extra in others:
        if extra.is_file() and extra.suffix in (".html", ".js", ".css", ".txt"):
            scanned.append((extra.relative_to(ROOT).as_posix(),
                            extra.read_text(encoding="utf-8", errors="replace").splitlines()))
    for rel, lines in scanned:
        for number, line in enumerate(lines, 1):
            for regex, what in FORBIDDEN:
                if regex.search(line):
                    errors.append(f"{rel}:{number}: {what} must not be in the docs")

    # --- 6. page shape ----------------------------------------------------------------------------
    for rel, page in content.items():
        if not page.title:
            errors.append(f"{rel}: no '# Title' line")
        if page.generated or rel in ("README.md", "_404.md"):
            continue
        if "<!-- sources:" not in page.text:
            warnings.append(f"{rel}: no '<!-- sources: ... -->' comment at the end")
        top = rel.split("/", 1)[0]
        budget = WORD_BUDGET.get(top)
        if budget and not rel.startswith(BUDGET_EXEMPT) and rel not in BUDGET_EXEMPT:
            if page.prose_words > budget * BUDGET_SLACK:
                warnings.append(f"{rel}: {page.prose_words} words of prose (budget {budget}): consider splitting")

    if args.words:
        for rel, page in sorted(content.items()):
            print(f"{page.prose_words:5d}  {rel}")

    if args.write_index:
        routes = ["/"] + [r for r in ordered_routes if r != "/"]
        out = ROOT / "assets" / "pages.js"
        out.parent.mkdir(parents=True, exist_ok=True)
        body = ",\n".join(f"  {json.dumps(r)}" for r in routes)
        out.write_text("// Written by tools/check_docs.py --write-index from the sidebars. Do not edit by hand.\n"
                       f"window.CW_DOCS_PAGES = [\n{body}\n];\n", encoding="utf-8", newline="\n")

    for warning in warnings:
        print("warning: " + warning)
    for error in errors:
        print("error: " + error)
    print(f"{len(content)} pages, {len(sidebars)} sidebars: {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
