#!/usr/bin/env python3
"""Build the name lists under guide/lists/ : models, materials, weapons, zombie types, effects.

Names only. Nothing but names, counts and hashes leaves the game install.

Reads (never writes):
  <cw-mod>/mapkit/godot/addons/mapkit/game_model_names.txt   the models' names
  <cw-mod>/mapkit/godot/addons/mapkit/mk_model_catalog.gd    the model picker's categories
  <game>/cw-mod/mapkit/brush_materials.txt                   the materials a brush can use (cwlink writes it)
  <game>/zone/zm_silver.ff, zm_common.ff                     through ffinfo and the two zone traces
and asks ACTS (acts -t lookup) for the name behind each asset hash.

Writes guide/lists/data/*.txt and the five generated pages. A part whose input is missing is skipped with a
note, and its page is left as it was.

Usage: python tools/gen_lists.py --cw-mod <path> [--game <game folder>] [--acts <acts.exe>]
"""
from __future__ import annotations

import argparse
import datetime
import json
import re
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "guide" / "lists"
DATA = OUT / "data"
ZONES = ("zm_silver", "zm_common")

WEAPON_FAMILIES = (
    ("ar_", "Assault rifles"), ("smg_", "Submachine guns"), ("tr_", "Tactical rifles"), ("lmg_", "Light machine guns"),
    ("sniper_", "Sniper rifles"), ("pistol_", "Pistols"), ("shotgun_", "Shotguns"), ("launcher_", "Launchers"),
    ("special_", "Special weapons"), ("melee_", "Melee weapons"), ("ww_", "Wonder weapons"),
    ("eq_", "Equipment"), ("hero_", "Support weapons"), ("zombie_perk_bottle_", "Perk bottles"),
)


def fnv63(text: str) -> int:
    value = 0xCBF29CE484222325
    for byte in text.encode():
        if 65 <= byte <= 90:
            byte += 32
        value = ((value ^ byte) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value & 0x7FFFFFFFFFFFFFFF


def write_lines(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def footer(sources: str) -> str:
    today = datetime.date.today().isoformat()
    return f"<!-- generated by tools/gen_lists.py on {today} from {sources}. Do not edit by hand. -->"


def embed(name: str) -> str:
    return f"[{name}](/guide/lists/data/{name} ':include :type=code text')"


# --- models ------------------------------------------------------------------------------------------

def models(cw_mod: Path) -> bool:
    names_file = cw_mod / "mapkit/godot/addons/mapkit/game_model_names.txt"
    catalog = cw_mod / "mapkit/godot/addons/mapkit/mk_model_catalog.gd"
    if not names_file.is_file():
        print(f"models: {names_file} not found, skipped")
        return False
    names = []
    for line in names_file.read_text(encoding="utf-8", errors="replace").splitlines():
        if len(line) > 17 and not line.startswith("#"):
            names.append(line[17:].strip())
    names = sorted(set(n for n in names if n))

    rules: list[tuple[str, re.Pattern]] = []
    if catalog.is_file():
        for label, pattern in re.findall(r'\["([^"]+)",\s*"((?:[^"\\]|\\.)*)"\]', catalog.read_text(encoding="utf-8")):
            rules.append((label, re.compile(pattern.replace("\\\\", "\\"))))
    counts: Counter[str] = Counter()
    examples: dict[str, list[str]] = {}
    for name in names:
        label = next((lab for lab, rx in rules if rx.search(name)), "Other")
        counts[label] += 1
        if len(examples.setdefault(label, [])) < 2 and not name.startswith("*"):
            examples[label].append(name)

    write_lines(DATA / "models.txt", names)
    page = [
        "# Models",
        "",
        f"> The names of {len(names)} game models a prop, a door or a wall buy can use. They come from Die Maschine's zone "
        "and the common Zombies zone.",
        "",
        "## Using a name",
        "",
        "- In the editor, a model field has a **Pick** button that shows these models with a picture. See "
        "[Props and models](/guide/mapping/props-models.md).",
        "- Typed by hand, a model is its name, or `#` and its 16-digit hash for a model that has no name here.",
        "- About 7 in 100 models have no known name. The picker lists them by hash.",
        "- A name that starts with `*` is a piece of Die Maschine's own world, cut by the game's map compiler.",
        "",
        "## By category",
        "",
        "The model picker sorts names into these groups. A model is in the first group whose pattern fits its name.",
        "",
        "| Category | Models | Examples |",
        "|---|---|---|",
    ]
    for label, _ in rules + [("Other", None)]:
        if counts[label]:
            shown = ", ".join(f"`{e}`" for e in examples.get(label, []))
            page.append(f"| {label} | {counts[label]} | {shown} |")
    page += [
        "",
        "## Every name",
        "",
        "Use your browser's search (Ctrl+F) inside the box. The site's own search does not look into it.",
        "",
        embed("models.txt"),
        "",
        footer("cw-mod mapkit/godot/addons/mapkit/game_model_names.txt and mk_model_catalog.gd"),
        "",
    ]
    (OUT / "models.md").write_text("\n".join(page), encoding="utf-8", newline="\n")
    print(f"models: {len(names)} names")
    return True


# --- materials ---------------------------------------------------------------------------------------

def materials(game: Path | None) -> bool:
    source = game / "cw-mod/mapkit/brush_materials.txt" if game else None
    if not source or not source.is_file():
        print("materials: <game>/cw-mod/mapkit/brush_materials.txt not found (cwlink build writes it), skipped")
        return False
    names = sorted({line.strip() for line in source.read_text(encoding="utf-8", errors="replace").splitlines()
                    if line.strip() and not line.startswith("#")})
    families: Counter[str] = Counter()
    for name in names:
        match = re.match(r"mc/mtl_+([a-z0-9]+)_", name)
        families[match.group(1) if match else "(other)"] += 1
    write_lines(DATA / "materials.txt", names)
    page = [
        "# Materials",
        "",
        f"> The names of {len(names)} game materials a brush or a mesh surface can use. They are the model materials "
        "(`mc/`) that Die Maschine's zone stores.",
        "",
        "## Using a name",
        "",
        "- On an `MkBrush`, set `game_material` to the name. Empty means the default, `mc/mtl_p7_cinder_block`.",
        "- On your own model, name the Blender material after a game material, or set the `MkMesh`'s `game_material`.",
        "- cwlink writes this same list to `<game>\\cw-mod\\mapkit\\brush_materials.txt` on your PC.",
        "- A material draws only when the shaders it needs are loaded. All of these are, in a map built on Die Maschine.",
        "",
        "More: [Materials and textures](/guide/mapping/materials-textures.md).",
        "",
        "## The commonest name families",
        "",
        "The word after `mc/mtl_` is usually the asset set the material came from.",
        "",
        "| Starts with | Materials |",
        "|---|---|",
    ]
    for family, count in families.most_common(12):
        page.append(f"| `mc/mtl_{family}_` | {count} |" if family != "(other)" else f"| other forms | {count} |")
    page += [
        "",
        "## Every name",
        "",
        "Use your browser's search (Ctrl+F) inside the box. The site's own search does not look into it.",
        "",
        embed("materials.txt"),
        "",
        footer("<game>/cw-mod/mapkit/brush_materials.txt, which cwlink writes from the player's own install (names only)"),
        "",
    ]
    (OUT / "materials.md").write_text("\n".join(page), encoding="utf-8", newline="\n")
    print(f"materials: {len(names)} names")
    return True


# --- assets by type, through ffinfo and ACTS ---------------------------------------------------------

def run_ffinfo(ffinfo: Path, game: Path, args: list[str]) -> bool:
    result = subprocess.run([str(ffinfo), "--game", str(game), *args], capture_output=True, text=True, errors="replace")
    return result.returncode == 0


def read_graph(path: Path) -> dict[str, dict[int, bool]]:
    """type -> {name hash: the zone stores it itself}."""
    out: dict[str, dict[int, bool]] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"\d+ (\w+) #([0-9a-f]{16}) \d+ (own|link)", line)
        if match:
            kind = out.setdefault(match.group(1), {})
            name = int(match.group(2), 16)
            kind[name] = kind.get(name, False) or match.group(3) == "own"
    return out


def acts_lookup(acts: str, hashes: set[int]) -> dict[int, str]:
    names: dict[int, str] = {}
    ordered = sorted(hashes)
    for start in range(0, len(ordered), 400):
        batch = [f"{h:x}" for h in ordered[start:start + 400]]
        try:
            result = subprocess.run([acts, "-t", "lookup", *batch], capture_output=True, text=True, errors="replace")
        except OSError:
            return names
        for line in result.stdout.splitlines():
            key, _, value = line.partition("=")
            try:
                name_hash = int(key, 16)
            except ValueError:
                continue
            value = value.strip()
            if value and "can't be find" not in value and fnv63(value) == name_hash:
                names[name_hash] = value
    return names


def entity_keys(entity: dict) -> dict:
    return {item[0]: item[2] for item in entity.get("keys", [])}


def from_install(cw_mod: Path, game: Path | None, acts: str) -> bool:
    ffinfo = cw_mod / "build/t9_vs2022/x64/ffinfo/ffinfo.exe"
    if not game or not ffinfo.is_file():
        print("weapons, zombie types, effects: need --game and a built ffinfo.exe, skipped")
        return False
    traces = {zone: game / f"cw-mod/mapkit/trace/{zone}.mktrace" for zone in ZONES}
    if not all(t.is_file() for t in traces.values()):
        print('weapons, zombie types, effects: need the zone traces of zm_silver and zm_common '
              '("mapkit_trace" in cw-mod.json), skipped')
        return False

    with tempfile.TemporaryDirectory(prefix="cwdocs-lists-") as work:
        work_dir = Path(work)
        graphs = {}
        for zone in ZONES:
            graph_file = work_dir / f"{zone}.graph"
            run_ffinfo(ffinfo, game, [zone, "--trace", str(traces[zone]), "--needs", "--needs-graph", str(graph_file)])
            if not graph_file.is_file():
                print(f"ffinfo wrote no graph for {zone}, skipped")
                return False
            graphs[zone] = read_graph(graph_file)
        entities_file = work_dir / "entities.json"
        run_ffinfo(ffinfo, game, ["zm_silver", "--entities", "--entities-json", str(entities_file)])
        entities = json.loads(entities_file.read_text(encoding="utf-8")) if entities_file.is_file() else []

    def assets(kind: str) -> dict[int, set[str]]:
        found: dict[int, set[str]] = {}
        for zone in ZONES:
            for name_hash, own in graphs[zone].get(kind, {}).items():
                if own:
                    found.setdefault(name_hash, set()).add(zone)
                else:
                    found.setdefault(name_hash, set())
        return found

    keyed = [entity_keys(e) for e in entities]
    classnames = Counter(k.get("classname", "") for k in keyed)
    wall_buys = sorted({k.get("script_noteworthy", "") for k in keyed if k.get("content_key") == "wallbuy_chalk"} - {""})
    spawner_classes = sorted(c for c in classnames if c.startswith("actor_spawner"))

    # --- weapons ---
    weapons = assets("weapon")
    weapon_names = acts_lookup(acts, set(weapons))
    named = sorted(weapon_names.values())
    write_lines(DATA / "weapons.txt", named)
    base = [n for n in named if n.endswith("_t9")]
    page = [
        "# Weapons",
        "",
        f"> The game's names for {len(named)} weapons, pieces of equipment and weapon-like items in the Zombies zones. "
        "A wall buy takes one of these names.",
        "",
        "## Wall buys you can place today",
        "",
        "A build moves Die Maschine's own wall buys to where you put yours, so a map can use these "
        f"{len(wall_buys)} weapons, once each. See [Gameplay objects](/guide/mapping/gameplay-objects.md).",
        "",
        "| `weapon` |",
        "|---|",
    ]
    page += [f"| `{w}` |" for w in wall_buys]
    page += [
        "",
        "## How the names are built",
        "",
        "A player weapon is `<class>_<role>_t9`. The same name with `_upgraded` is its Pack-a-Punched form, going by the name.",
        "",
        "| Starts with | What | Names |",
        "|---|---|---|",
    ]
    for prefix, label in WEAPON_FAMILIES:
        count = sum(1 for n in named if n.startswith(prefix))
        if count:
            page.append(f"| `{prefix}` | {label} | {count} |")
    page += [
        "",
        f"{len(base)} names end in `_t9` and are not upgraded forms: the weapons a player holds. The rest are upgraded "
        "forms, equipment, field upgrades, scorestreaks, perk bottles and the weapons the zombies and bosses use.",
        "",
        "## Every name",
        "",
        f"{len(weapons) - len(named)} more weapon assets are known by hash only and are left out.",
        "",
        embed("weapons.txt"),
        "",
        footer("the weapon assets of zm_silver and zm_common (ffinfo --needs-graph), named by ACTS; "
               "the wall buys from Die Maschine's entity list"),
        "",
    ]
    (OUT / "weapons.md").write_text("\n".join(page), encoding="utf-8", newline="\n")
    print(f"weapons: {len(named)} of {len(weapons)} named, {len(wall_buys)} wall buys")

    # --- zombie types ---
    ai = assets("aitype")
    ai_names = acts_lookup(acts, set(ai))
    candidates = {c[len("actor_"):] for c in spawner_classes}
    cwlink = cw_mod / "mapkit/cwlink/main.cpp"
    if cwlink.is_file():
        candidates |= set(re.findall(r'"(spawner_[a-z0-9_]+)"', cwlink.read_text(encoding="utf-8", errors="replace")))
    for candidate in candidates:
        if fnv63(candidate) in ai:
            ai_names.setdefault(fnv63(candidate), candidate)
    rows = sorted((name, sorted(ai[h])) for h, name in ai_names.items())
    write_lines(DATA / "ai-types.txt", [name for name, _ in rows])
    page = [
        "# Zombie types",
        "",
        f"> The AI types of the Zombies zones: {len(ai)} in all, {len(rows)} of them known by name.",
        "",
        "## How a map gets its zombies",
        "",
        "- An **AI type** is an asset: the body, the behaviour and the animations of one kind of enemy.",
        "- A level spawns them from **spawner templates**: entities whose class is `actor_` and the AI type's name.",
        "- A mapkit map keeps Die Maschine's templates. You do not pick the zombie type per spawner yet: the round "
        "logic of the shared Zombies scripts decides what comes.",
        "- A map that no longer loads Die Maschine's zones has only the common zone's AI types. cwlink then swaps a "
        "template whose type would be missing for the closest common one.",
        "",
        "## Die Maschine's spawner templates",
        "",
        "| Template class | Count | In a mapkit map |",
        "|---|---|---|",
    ]
    stand_ins = {}
    if cwlink.is_file():
        stand_ins = dict(re.findall(r'\{\s*"(spawner_[a-z0-9_]+)",\s*"(spawner_[a-z0-9_]+)"\s*\}',
                                    cwlink.read_text(encoding="utf-8", errors="replace")))
    for cls in spawner_classes:
        ai_type = cls[len("actor_"):]
        note = f"becomes `{stand_ins[ai_type]}`" if ai_type in stand_ins else "kept"
        page.append(f"| `{cls}` | {classnames[cls]} | {note} |")
    page += [
        "",
        "## Named AI types",
        "",
        "| AI type | Stored in |",
        "|---|---|",
    ]
    for name, zones in rows:
        page.append(f"| `{name}` | {', '.join(zones) if zones else 'linked from another zone'} |")
    page += [
        "",
        f"The other {len(ai) - len(rows)} are known by hash only.",
        "",
        footer("the aitype assets of zm_silver and zm_common (ffinfo --needs-graph), named by ACTS and by the spawner "
               "classes of Die Maschine's entity list; the stand-ins from cw-mod mapkit/cwlink/main.cpp"),
        "",
    ]
    (OUT / "zombies.md").write_text("\n".join(page), encoding="utf-8", newline="\n")
    print(f"zombie types: {len(rows)} of {len(ai)} named")

    # --- effects ---
    fx = assets("fx")
    fx_names = sorted(acts_lookup(acts, set(fx)).values())
    write_lines(DATA / "effects.txt", fx_names)
    page = [
        "# Effects",
        "",
        f"> The Zombies zones hold {len(fx)} particle effects. {len(fx_names)} are known by name; the rest only by hash.",
        "",
        "## What you can do with them today",
        "",
        "Nothing from the editor yet: mapkit has no node that places an effect, and a built map's list of placed "
        "ambient effects is empty. A level script can play an effect the same way the game's own scripts do, by name. "
        "See [Effects and wind](/guide/mapping/effects-wind.md).",
        "",
        "## The names we have",
        "",
        embed("effects.txt"),
        "",
        footer("the fx assets of zm_silver and zm_common (ffinfo --needs-graph), named by ACTS"),
        "",
    ]
    (OUT / "effects.md").write_text("\n".join(page), encoding="utf-8", newline="\n")
    print(f"effects: {len(fx_names)} of {len(fx)} named")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cw-mod", required=True, type=Path, help="path to a cw-mod checkout (read only)")
    parser.add_argument("--game", type=Path, help="the game folder (read only), for the lists that need the install")
    parser.add_argument("--acts", default="acts", help="the ACTS executable (default: acts on PATH)")
    args = parser.parse_args()
    cw_mod = args.cw_mod.resolve()
    game = args.game.resolve() if args.game else None
    DATA.mkdir(parents=True, exist_ok=True)
    models(cw_mod)
    materials(game)
    from_install(cw_mod, game, args.acts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
